#!/bin/bash

set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH
mkdir -p build
now=$(date +'%Y-%m-%d_%T')
GOOS=$1 GOARCH=$2 go build  -ldflags " -X github.com/singnet/snet-daemon/config.sha1Revision=`git rev-parse HEAD` -X github.com/singnet/snet-daemon/config.versionTag=`git describe --tag` -X github.com/singnet/snet-daemon/config.buildTime=$now" -o build/snetd-$1-$2 snetd/main.go
popd


