#!/usr/bin/env bash
set -ex
PARENT_PATH="$(dirname "$(cd "$("dirname" "$0")"; pwd -P)")"
pushd "$PARENT_PATH"


if [ $# -lt 1 ]
  then
    echo "arguments expected are of the form <VERSION> for the build script , as an example: '/scripts/build-all v6.1.0'"
    exit 1
fi

 ./scripts/build darwin	amd64 $1
 ./scripts/build darwin	arm64 $1
 ./scripts/build linux 386 $1
 ./scripts/build linux	amd64 $1
 ./scripts/build linux	arm $1
 ./scripts/build linux	arm64 $1
 ./scripts/build windows	amd64 $1
 ./scripts/build windows	arm $1
 ./scripts/build windows	arm64 $1

# ./scripts/build windows	386 $1
# ./scripts/build netbsd	amd64 $1
# ./scripts/build openbsd	amd64 $1
# ./scripts/build dragonfly amd64 $1
# ./scripts/build freebsd 386 $1
# ./scripts/build freebsd amd64 $1
# ./scripts/build freebsd arm $1
