#!/bin/bash

set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

go get google.golang.org/protobuf@latest
go get google.golang.org/grpc@latest
go get golang.org/x/lint/golint@latest

go install github.com/ethereum/go-ethereum/cmd/abigen@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

pushd resources/blockchain
npm install
popd

go generate ./...
popd