#!/bin/bash

set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

go get -d github.com/golang/protobuf/protoc-gen-go@v1.4.0
go get -d github.com/ethereum/go-ethereum/cmd/abigen@v1.9.0
go get -d google.golang.org/grpc@v1.16.0
go get -d golang.org/x/lint/golint

pushd resources/blockchain
npm install
popd

go generate ./...
popd
