#!/usr/bin/env bash
set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd "$PARENT_PATH"

go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

go generate ./...
popd
