#!/bin/bash

set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH
mkdir -p build
mkdir -p build/snetd-$1/darwin-amd64
mkdir -p build/snetd-$1/linux-amd64
cp build/snetd-darwin-amd64 build/snetd-$1/darwin-amd64/snetd
cp build/snetd-linux-amd64 build/snetd-$1/linux-amd64/snetd
pushd build/snetd-$1
tar -zcvf ../snetd-$1.tar.gz ./*
popd
popd
