#!/bin/bash

set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH
# Run golint
# NOTE: currently we are just printing lint violations, not failing the test if any errors are present
./scripts/lint

# Run integration tests
go get golang.org/x/tools/cmd/cover
go get github.com/mattn/goveralls
for d in */ ; do
  for entry in "$d"/*;do
	  if `[[ $entry =~ [a-zA-Z-]{1,}(_test.go)$  ]]`;then echo `go test -v ./${d: 0:-1} -coverprofile ${d: 0:-1}.part`;fi
  done
done
echo "mode: set">>coverage.out
grep -h -v "mode: set" *.part >>coverage.out
/go/bin/goveralls -coverprofile=coverage.out -service=circleci -repotoken ${COVERALLS_REPO_TOKEN}
popd