// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package echoservice is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	EchoEnvelope
*/
package echoservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoEnvelope struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *EchoEnvelope) Reset()                    { *m = EchoEnvelope{} }
func (m *EchoEnvelope) String() string            { return proto.CompactTextString(m) }
func (*EchoEnvelope) ProtoMessage()               {}
func (*EchoEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoEnvelope) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoEnvelope)(nil), "EchoEnvelope")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EchoService service

type EchoServiceClient interface {
	// NOTE: we wouldn't normally return the same type as the request, but to
	// simplify integration testing sometimes we stub out the response as the
	// request.
	Echo(ctx context.Context, in *EchoEnvelope, opts ...grpc.CallOption) (*EchoEnvelope, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoEnvelope, opts ...grpc.CallOption) (*EchoEnvelope, error) {
	out := new(EchoEnvelope)
	err := grpc.Invoke(ctx, "/EchoService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EchoService service

type EchoServiceServer interface {
	// NOTE: we wouldn't normally return the same type as the request, but to
	// simplify integration testing sometimes we stub out the response as the
	// request.
	Echo(context.Context, *EchoEnvelope) (*EchoEnvelope, error)
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe0, 0xe2, 0x71, 0x4d, 0xce, 0xc8, 0x77, 0xcd, 0x2b,
	0x4b, 0xcd, 0xc9, 0x2f, 0x48, 0x15, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x8d, 0x8c, 0xb9, 0xb8, 0x41, 0x2a, 0x83,
	0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x54, 0xb8, 0x58, 0x40, 0x5c, 0x21, 0x5e, 0x3d, 0x64,
	0xfd, 0x52, 0xa8, 0x5c, 0x27, 0xde, 0x28, 0xee, 0xd4, 0xe4, 0x8c, 0xfc, 0x62, 0x88, 0xa6, 0x24,
	0x36, 0xb0, 0xa5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xe7, 0xd5, 0x1a, 0x81, 0x00,
	0x00, 0x00,
}
